# Copyright 2026 wyteroze. Licensed under the Apache License, Version 2.0.
# Le kebab config. You can adjust various settings in this file to your liking.

[window]
# The rendering resolution. The window size is double this.
# Expects two integers, width and height. Default: [ 540, 360 ]
resolution = [ 540, 360 ]

# The target FPS of the engine. Expects an integer. Default: 60
fps = 120

# The scale factor of the window. The window's size will be
# resolution times this value
scale = 2.0
