#!/usr/bin/env python3
# Copyright 2026 wyteroze. Licensed under the Apache License, Version 2.0.
"""Generates a `map.toml` from a font2bitmap export

Only the Construct3 export is required. It carries most info, but everything else is recovered:

  * character order: defaults to font2bitmap's character order.
    Override with --chars if you exported with a different order or set.
  * cell size:  auto detected from the sheet, but only works for square cells.
    Pass --cell WxH (ex. 16x18) for non square grids
  * glyphs-per-row:  sheet_width // cell_width
"""

import argparse
import json
import math
import os
import re
import struct
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required (install via `pip install pillow`)")

DEFAULT_CHARS = "".join(chr(c) for c in range(0x20, 0x7F))

def read_arg(value: str) -> str:
    if value.startswith("@"):
        with open(value[1:], encoding="utf-8") as f:
            return f.read().rstrip("\r\n")
    return value


def parse(src: str) -> dict:
    try:
        groups = json.loads(src)
    except json.JSONDecodeError as e:
        sys.exit(f"error: Construct3 export is not valid JSON: {e}")
    adv = {}
    for advance, chars in groups:
        rounded = int(math.floor(float(advance) + 0.5))
        for c in chars:
            adv[c] = rounded
    return adv

def image_size(path: str):
    if path.lower().endswith(".bmp"):
        with open(path, "rb") as f:
            data = f.read(26)
        if data[:2] != b"BM":
            sys.exit(f"error: {path} is not a BMP")
        return struct.unpack("<i", data[18:22])[0], struct.unpack("<i", data[22:26])[0]
    with Image.open(path) as im:
        return im.size


def parse_cell(spec: str):
    m = re.fullmatch(r"\s*(\d+)\s*(?:[xX,]\s*(\d+))?\s*", spec)
    if not m:
        sys.exit(f"error: --cell must look like '30' or '16x18', got {spec!r}")
    w = int(m.group(1))
    return w, int(m.group(2)) if m.group(2) else w


def detect_square_cell(img_w: int, img_h: int, nglyphs: int):
    found = []
    for per_row in range(1, nglyphs + 1):
        if img_w % per_row:
            continue
        cw = img_w // per_row
        rows = math.ceil(nglyphs / per_row)
        if rows == 0 or img_h % rows:
            continue
        if cw == img_h // rows:
            found.append((cw, cw))
    if len(found) == 1:
        return found[0]
    return None


def esc(c: str) -> str:
    return {"\\": "\\\\", '"': '\\"'}.get(c, c)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("image", help="path to the sheet image")
    ap.add_argument("construct3", help="Construct3 [[adv,chars],...] JSON, or @file")
    ap.add_argument("--cell", help="cell size 'WxH' (ex. 16x18). default: auto-detects square cells")
    ap.add_argument("--chars", help="character order (or @file). default: printable ASCII `space` to `~`")
    ap.add_argument("--name", help="font name. default: 'font'")
    ap.add_argument("--out", help="output map.toml path. default: map.toml beside the image")
    ap.add_argument("--line-height", type=int, help="line height in px. default: cell height")
    args = ap.parse_args()

    advances = parse(read_arg(args.construct3))
    img_w, img_h = image_size(args.image)

    chars = read_arg(args.chars) if args.chars else DEFAULT_CHARS

    if args.cell:
        cell_w, cell_h = parse_cell(args.cell)
    else:
        detected = detect_square_cell(img_w, img_h, len(chars))
        if not detected:
            sys.exit(
                f"error: could not auto-detect a square cell for a {img_w}x{img_h} sheet "
                f"with {len(chars)} glyphs, pass --cell WxH explicitly"
            )
        cell_w, cell_h = detected

    if img_w % cell_w or img_h % cell_h:
        print(
            f"warning: sheet {img_w}x{img_h} is not an exact multiple of the "
            f"{cell_w}x{cell_h} cell size",
            file=sys.stderr,
        )
    per_row = img_w // cell_w
    if per_row == 0:
        sys.exit(f"error: cell width {cell_w} is wider than the sheet ({img_w}px)")

    capacity = per_row * (img_h // cell_h)
    if len(chars) > capacity:
        sys.exit(
            f"error: {len(chars)} glyphs won't fit in a {per_row}x{img_h // cell_h} grid "
            f"({capacity} cells)"
        )

    missing = [c for c in chars if c not in advances]
    if missing:
        print(
            "warning: no advance for %s, using cell width %d"
            % (", ".join(repr(c) for c in missing), cell_w),
            file=sys.stderr,
        )

    font_name = args.name or "font"
    map_field = os.path.basename(args.image)
    line_height = args.line_height if args.line_height is not None else cell_h
    out_path = args.out or os.path.join(os.path.dirname(args.image), "map.toml")

    lines = [
        "# Generated by scripts/helpers/export_to_map.py",
        f"# Per row = {per_row}, Grid width = {cell_w}, Grid height = {cell_h}",
        "",
        "[info]",
        f'name = "{font_name}"',
        f'map = "{map_field}"',
        f"line_height = {line_height}",
        "",
        "[glyphs]",
    ]

    for i, c in enumerate(chars):
        col, row = i % per_row, i // per_row
        adv = advances.get(c, cell_w)
        lines.append(
            f'"{esc(c)}" = [ [{col * cell_w}, {row * cell_h}], [{cell_w}, {cell_h}], {adv} ]'
        )

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"wrote {out_path}: {len(chars)} glyphs, {cell_w}x{cell_h} cells, {per_row}/row")


if __name__ == "__main__":
    main()
