--[[
Copyright 2026 wyteroze. Licensed under the Apache License, Version 2.0.
--]]

--- @meta Widget
-- This file is for the Lua Language Server, do not require it

--- Where a widget is anchored, both to its container and as its own pivot.
--- For example, "BottomRight" pins the widget's bottom right corner to the bottom right of its container.
--- @alias Anchor "TopLeft" | "Top" | "TopRight" | "Left" | "Center" | "Right" | "BottomLeft" | "Bottom" | "BottomRight"

--- The base of every UI element. Each widget kind (Panel, Label, Button, Canvas,
--- Container, ScrollContainer) inherits from Widget and adds its own fields.
---
--- Widgets form a tree. Widgets created from `window.UI` are roots, and widgets
--- created from a container (with the builders below) are children of the container.
--- A child's position is relative to its parent container rather than the whole window.
--- @class Widget
--- The anchor point the widget is positioned from.
--- @field Anchor Anchor
--- The pixel offset from the anchor.
--- @field Offset Vec2
--- The widget's resolved position, in pixels.
--- @field ResolvedPosition Vec2
--- The widget's resolved size, in pixels.
--- @field ResolvedSize Vec2
--- The widget's size in pixels.
--- @field Size Vec2
--- Whether the widget and its contents is drawn.
--- @field Visible boolean
--- "Attaches" a function to when the left mouse button is pressed over this widget.
--- The callback is called with the pointer position.
--- @field OnMouseDown fun(self: Widget, callback: fun(pos: Vec2))
--- "Attaches" a function to when the left mouse button is released after a press that started on this widget.
--- The callback is called with the pointer position.
--- @field OnMouseUp fun(self: Widget, callback: fun(pos: Vec2))
--- "Attaches" a function to mouse movement while this widget is held down.
--- The callback is called with the movement delta, in screen pixels. This is mainly useful for window dragging.
--- @field OnDrag fun(self: Widget, callback: fun(delta: Vec2))
--- "Attaches" a function to when the cursor enters this widget.
--- @field OnMouseEnter fun(self: Widget, callback: fun())
--- "Attaches" a function to when the cursor leaves this widget.
--- @field OnMouseLeave fun(self: Widget, callback: fun())
--- Removes and destroys this widget (and its children). Any remaining references to it become invalid.
--- @field Remove fun(self: Widget)

--- A colored rectangle, with an optional border.
--- @class Panel : Widget
--- The background fill color.
--- @field Bg Color
--- The border color. If nil, no border is drawn.
--- @field BorderColor? Color
--- The border size.
--- @field BorderSize integer
--- Determines if the top side of the border is drawn.
--- @field BorderTop boolean
--- Determines if the bottom side of the border is drawn.
--- @field BorderBottom boolean
--- Determines if the left side of the border is drawn.
--- @field BorderLeft boolean
--- Determines if the right side of the border is drawn.
--- @field BorderRight boolean

--- Text that sizes itself from its font and content, so it has no size of its own.
--- @class Label : Widget
--- The displayed text.
--- @field Text string
--- The color the text is drawn in.
--- @field TextColor Color
--- The font used to render the text.
--- @field Font Font
--- The font's scale, default is 1.
--- @field FontScale integer
--- A clickable rectangle with text.

--- @class Button : Widget
--- The background fill color.
--- @field Bg Color
--- The border color. If nil, no border is drawn.
--- @field BorderColor? Color
--- The border size.
--- @field BorderSize integer
--- --- Determines if the top side of the border is drawn.
--- @field BorderTop boolean
--- Determines if the bottom side of the border is drawn.
--- @field BorderBottom boolean
--- Determines if the left side of the border is drawn.
--- @field BorderLeft boolean
--- Determines if the right side of the border is drawn.
--- @field BorderRight boolean
--- The displayed text.
--- @field Text string
--- The color the text is drawn in.
--- @field TextColor Color
--- The font used to render the text.
--- @field Font Font
--- The font's scale, default is 1.
--- @field FontScale integer
--- "Attaches" a function to the button's click event.
--- The callback is called every time the button is clicked.
--- @field OnClick fun(self: Button, callback: fun())

--- A drawing surface, where you can "paint" all types of shapes on it.
--- @class Canvas : Widget
--- "Attaches" a function to the canvas' paint event.
--- The callback is called every frame with a Painter to draw the canvas' contents with.
--- The Painter is only valid for each OnPaint callback. Do not store it for use later.
--- @field OnPaint fun(self: Canvas, callback: fun(painter: Painter))

--- Draws an image, scaled to fit the widget's size.
--- @class Image : Widget
--- The image drawn.
--- @field Image ImageData
--- Tints the image with this color. If nil, the image is drawn as-is
--- @field Tint? Color

--- Holds child widgets and arranges them. Create children with the builder methods.
--- @class Container : Widget
--- The background fill color.
--- @field Bg Color
--- The border color. If nil, no border is drawn.
--- @field BorderColor? Color
--- The border size.
--- @field BorderSize integer
--- --- Determines if the top side of the border is drawn.
--- @field BorderTop boolean
--- Determines if the bottom side of the border is drawn.
--- @field BorderBottom boolean
--- Determines if the left side of the border is drawn.
--- @field BorderLeft boolean
--- Determines if the right side of the border is drawn.
--- @field BorderRight boolean
--- Whether children are clipped to this container's bounds.
--- @field Clip boolean
--- Where a stack's children sit along the stacking axis. The other axis is placed by
--- each child's own Anchor
--- @field Align "Start" | "Center" | "End"
--- Creates a Panel inside this container. A panel is a colored rectangle, with an optional border.
--- @field Panel fun(self: Container, anchor: Anchor, offset: Vec2, size: Vec2): Panel
--- Creates a Label inside this container. A label sizes itself from its font and text, so no size is given.
--- @field Label fun(self: Container, anchor: Anchor, offset: Vec2, text: string): Label
--- Creates a Button inside this container. Use OnClick event to respond to clicks.
--- @field Button fun(self: Container, anchor: Anchor, offset: Vec2, size: Vec2, text: string): Button
--- Creates a Canvas inside this container. Use the returned canvas' OnPaint event to draw into it.
--- @field Canvas fun(self: Container, anchor: Anchor, offset: Vec2, size: Vec2): Canvas
--- Creates an Image inside this container, drawing the given image.
--- @field Image fun(self: Container, anchor: Anchor, offset: Vec2, size: Vec2, image: ImageData): Image
--- Creates a Container inside this container.
--- @field Container fun(self: Container, anchor: Anchor, offset: Vec2, size: Vec2): Container
--- Creates a ScrollContainer inside this container.
--- @field ScrollContainer fun(self: Container, anchor: Anchor, offset: Vec2, size: Vec2): ScrollContainer
--- Arranges children in a top-to-bottom stack, with `padding` pixels between each.
--- @field StackVertical fun(self: Container, padding: number)
--- Arranges children in a left-to-right stack, with `padding` pixels between each.
--- @field StackHorizontal fun(self: Container, padding: number)
--- Places children at their own anchor and offset, ignoring stacking. This is the default.
--- @field AbsoluteLayout fun(self: Container)
--- The number of children in this container.
--- @field GetChildCount fun(self: Container): integer
--- Gets a child by its index, starting at 1.
--- @field GetChild fun(self: Container, index: integer): Widget
--- Removes and destroys every child of this container.
--- @field Clear fun(self: Container)

--- A container whose contents can be scrolled with the mouse wheel. It clips its
--- children by default.
--- @class ScrollContainer : Container
--- The scroll offset of the content, in pixels. Usually driven by the mouse wheel,
--- but you may set it yourself. It is clamped to the size of the content.
--- @field Scroll Vec2
