--[[
Copyright 2026 wyteroze. Licensed under the Apache License, Version 2.0.
--]]

--- @meta Window
-- This file is for the Lua Language Server, do not require it

--- A window's UI namespace, used to create widgets inside the window.
--- Accessed via `window.UI`.
--- @class WindowUI
---
--- Every widget made here is a root, positioned relative to the whole window.
--- To nest widgets, make a Container (or a ScrollContainer) and use its own
--- builder methods to add children.
---
--- Creates a Panel in this window. A panel is a colored rectangle, with an optional border.
--- @field Panel fun(self: WindowUI, anchor: Anchor, offset: Vec2, size: Vec2): Panel
--- Creates a Label in this window. A label sizes itself from its font and text, so no size is given.
--- @field Label fun(self: WindowUI, anchor: Anchor, offset: Vec2, text: string): Label
--- Creates a Button in this window.
--- @field Button fun(self: WindowUI, anchor: Anchor, offset: Vec2, size: Vec2, text: string): Button
--- Creates a Canvas in this window.
--- @field Canvas fun(self: WindowUI, anchor: Anchor, offset: Vec2, size: Vec2): Canvas
--- Creates an Image in this window, drawing the given image.
--- @field Image fun(self: WindowUI, anchor: Anchor, offset: Vec2, size: Vec2, image: ImageData): Image
--- Creates a Container in this window, which holds and arranges child widgets.
--- @field Container fun(self: WindowUI, anchor: Anchor, offset: Vec2, size: Vec2): Container
--- Creates a ScrollContainer in this window, a container whose contents scroll with the mouse wheel.
--- @field ScrollContainer fun(self: WindowUI, anchor: Anchor, offset: Vec2, size: Vec2): ScrollContainer

--- A window's input namespace. Only receives input while the window is focused.
--- Accessed via `window.Input`.
--- @class WindowInput
---
--- Whether the mouse is locked to this window (relative mode) while it is
--- focused. Useful for first-person camera look.
--- @field MouseLocked boolean
--- Whether the mouse cursor is visible.
--- @field MouseVisible boolean
---
--- Connects a callback to when an input begins (ex. key pressed).
--- @field OnBegin fun(self: WindowInput, code: InputCode, callback: fun(input: Input))
--- Connects a callback to when an input ends (ex. key released).
--- @field OnEnd fun(self: WindowInput, code: InputCode, callback: fun(input: Input))
--- Connects a callback to when an input changes (ex. mouse movement).
--- @field OnChange fun(self: WindowInput, code: InputCode, callback: fun(input: Input))
--- Checks whether an input is currently down.
--- @field IsDown fun(self: WindowInput, code: InputCode): boolean
--- Gets an input's current value.
--- @field GetValue fun(self: WindowInput, code: InputCode): number

--- Represents a window. A window owns everything shown inside it; the scene
--- it renders, the camera it renders the scene from, UI widgets, and the
--- input it receives while focused.
---
--- Windows are independent. The same Scene can be assigned to several windows at
--- once, each with its own Camera, so two windows can look into one shared world
--- at different points.
--- @class Window
---
--- The scene rendered in this window. Set to nil for a UI-only window (no 3D).
--- The same Scene may be assigned to multiple windows at once.
--- @field Scene? Scene
---
--- The camera this window renders its scene from. The same camera may be assigned
--- to multiple windows at once.
--- @field Camera? Camera
---
--- The window's title text.
--- @field Title string
---
--- The window's top-left position on screen, in pixels.
--- @field Position Vec2
---
--- Widget creation for this window. See WindowUI.
--- @field UI WindowUI
--- Per-window input. See WindowInput.
--- @field Input WindowInput
---
--- Attaches a function to this window's per frame update. It is called once per
--- frame with the delta time (in seconds) for as long as the window is open.
--- Use this for per window logic; for example moving this window's Camera
--- from this window's input. For scene-wide updates, use Scene:OnUpdate instead.
--- @field OnUpdate fun(self: Window, callback: fun(delta: number))
---
--- Attaches a function to when this window is closed.
--- The function is called right before the window is truly closed.
--- @field OnClose fun(self: Window, callback: fun())
---
--- Attaches a function to when this window is focused.
--- @field OnFocus fun(self: Window, callback: fun())
---
--- Attaches a function to when this window loses focus.
--- @field OnFocusLost fun(self: Window, callback: fun())
---
--- Closes and destroys the window. Any remaining references to it become invalid.
--- @field Close fun(self: Window)
---
--- Minimizes the window.
--- @field Minimize fun(self: Window)
--- Maximizes the window.
--- @field Maximize fun(self: Window)
---
--- Focuses the window, both bringing it to front and capturing input.
--- @field Focus fun(self: Window)

--- Factory for creating windows. The engine opens no window on its own; the
--- first Window.new call creates the game window.
--- @class WindowLib
Window = {}

--- Creates and opens a new window. Width and height determine the internal resolution,
--- and the optional `scale` (default is 1.0) determines the window size multiplier.
--- @param title string
--- @param width integer
--- @param height integer
--- @param scale number?
--- @param decorated boolean?
--- @param transparent boolean?
--- @param resizable boolean?
--- @return Window
function Window.new(title, width, height, scale, decorated, transparent, resizable) end
